### ISSUE TITLE
Change default keyboard to be US English instead of UK English

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/pi-gen#14]
[Found this in a thread about installation problems](https://www.reddit.com/r/homeassistant/comments/5r7zwb/home_assistant_is_way_harder_than_i_thought/dd5568d/). Can we change the default keyboard? Almost 40% of the current install base is in the US.

**Comment by Landrash** [comment]
Should be fixed in future images since it was caused by an upstream bug in the buildscript.
