### ISSUE TITLE
Keyboard layout first boot

### ISSUE THREAD

**Issue by DavidDeSloovere** [home-assistant/pi-gen#3]
Keyboard layout is probably US. I'm on a Belgian keyboard, that is Azerty... yes I know ;-) ...

I don't know if it is even possible, but would be great to get at least a message about this, especially because there is an 'A' in the default password.
What would be event better, is to ask for the keyboard layout, but that's probably too much work for the return. 

I'm logging in onto the pi itself, not via ssh.

**Comment by Landrash** [comment]
Since the image is built in the same way as the raspbian image it should work the same.
To change the layout after you succeed in login in run the following command to change the keyboard layout.
```bash
sudo dpkg-reconfigure keyboard-configuration
```

**Comment by Landrash** [comment]
Closed with https://github.com/home-assistant/home-assistant.github.io/pull/1459.
No changes will be done to stock image to prevent deviating to much from the stock Raspbian image.
