### ISSUE TITLE
Add nmap to HASSbian

### ISSUE THREAD

**Issue by fabaff** [home-assistant/pi-gen#5]
Original issue: https://github.com/home-assistant/home-assistant.github.io/issues/1510

**Comment by Landrash** [comment]
Won't do this since it's a bad idea to pre-install tools that are not used by default. 
Only tools that will potentially be pre-installed are the ones that requires compiling or for some other reason needs extra setup on the raspberry pi.

**Comment by mkuoppa** [comment]
Well I only did it 3 times with the same result. Could my problems be related to hardware, network???

**Comment by Landrash** [comment]
It's possible. If you got local access to your pi you could verify that ssh
is running after boot.
SSH can have a small delay also since new ssh keys are generated on first
boot.
