### ISSUE TITLE
SSH not possible on first boot

### ISSUE THREAD

**Issue by mkuoppa** [home-assistant/pi-gen#6]
Not possible to SSH to RP3 after loading the image to an SD card and booting the first time. Powering off/on one time is required for SSH to work. Though Home Assistant web interface is working at first boot.

**Comment by Landrash** [comment]
On first boot the image resized it self and reboots.
On second reboot (I've tested this to many times to count) ssh is available and HA becomes available as soon as it's installed.
Did this as latest yesterday while working on an updated image and on the current released image.
