### ISSUE TITLE
Add additional scripts

### ISSUE THREAD

**Issue by dale3h** [home-assistant/pi-gen#7]
As per your request, please consider adding the following to Hassbian:

`hassctl` - http://pastebin.com/CwXh0vfN
`mosquitto` installer - https://github.com/dale3h/homeassistant-config/blob/master/wizard/mosquitto-wizard.sh
`open-zwave` installer: https://github.com/dale3h/homeassistant-config/blob/0d4358de498217755a2a027a22ced555892bc3d4/wizard/openzwave-hassbian.sh

If I think of any more, I'll be sure to comment here.

Thanks @Landrash for your amazing work on this image!

**Comment by subutux** [comment]
Maybe add some check if these scripts are run as root:
```bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root or use \"sudo ${0} ${*}\"" 1>&2
   exit 1
fi
```

**Comment by Landrash** [comment]
Scripts are being added one by one into the installer. Thanks for the hard work @dale3h and for the idea @subutux .
